# Generated by Django 3.0 on 2020-05-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_text', models.CharField(max_length=200)),
                ('order_date', models.DateTimeField(verbose_name='Date and time of the order')),
                ('notes', models.TextField(blank=True, verbose_name='Additional information')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
